### ISSUE TITLE
Header options are converted into lowercase

### ISSUE THREAD

**Issue by flyingcactuscloud** [ZimCodes/Zeiver#4]
### OD Support

- [X] OD

### Summary

e.g. basic auth fails, because the Authorization header is case sensitive

### Details

Today I tried to scrape an OD using your Zeiver application and it failed. The OD is password protected with basic authentication. I know the password, but there is no native way to supply password options for the OD in Zeiver, as far as I know (I saw the --auth-proxy option for the proxy, but there is no --auth for the OD).

So I tried to insert the Authorization header manually. However, the header options converted to lowercase by Zeiver, thus making basic auth fail.

Version: Zeiver 0.8.3

**Comment by ZimCodes** [comment]
@flyingcactuscloud First and foremost, thank you for taking the time to create this issue.

> the header options converted to lowercase by Zeiver, thus making basic auth fail.

This is true.

Zeiver makes both the header name/value entirely lowercase. This is because when creating Zeiver, it did not occur to me the header values will incorporate characters that are uppercase as well. _No idea how I came to that conclusion. Maybe the `Accept` header let you get away with it? ❓_  

In any case, a fix will be coming soon with the next update.

> there is no native way to supply password options for the OD in Zeiver, as far as I know (I saw the --auth-proxy option for the proxy, but there is no --auth for the OD).

Thank you for mentioning this. I will be adding an authorization option along with the fix soon.

### Side Note
> The OD is password protected with basic authentication.

This sounds like a _Closed Directory_ rather than an _Open_ one, as it requires authentication to use.

**Comment by ZimCodes** [comment]
For progress, please check pr #5 as it will address this issue.

**Comment by flyingcactuscloud** [comment]
I appreciate the instant fix. With the new version auth works beautifully.

The server software is listed as compatible OD, true you might say it's not an open directory anymore but I'd say basic authentication ain't something which is very rare in the web. To be honest I did not spend a lot of thought on this, and therefore did not think of my request being out of scope. Thanks anyways!
